apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: decision-engine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sujeetmadihalli/distributed-decision-engine.git
    targetRevision: main
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: decision-engine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
